name: E2E

on:
  pull_request:
    branches:
      - next
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run e2e
